name: Deploying The Frontend

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    DOCKER_IMAGE_NAME: root 
    VIRTUAL_MACHINE_USERNAME: ubuntu

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Log in to dockehub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./docker-files/dockerfile.frontend
                  push: true
                  no-cache: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

            - name: Deploy to Virtual Machine
              uses: appleboy/ssh-action@master
              env:
                  DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
                  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
              with:
                  host: ${{ secrets.HOST_IP }}
                  key: ${{ secrets.SSH_KEY }}
                  username: ${{ env.VIRTUAL_MACHINE_USERNAME }}
                  envs: DOCKER_IMAGE_NAME, DOCKER_HUB_USERNAME
                  script: |
                      echo "Stopping and Removing old Container"
                      sudo docker stop $DOCKER_IMAGE_NAME || true
                      sudo docker rm   $DOCKER_IMAGE_NAME || true

                      echo "Removing old repl Image" 
                      sudo docker rmi $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest || true

                      echo "Pulling new Image" 
                      sudo docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest

                      echo "Starting new Frontend Container"
                      sudo docker run -d --name $DOCKER_IMAGE_NAME -p 3000:3000 \
                          $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest

                       echo "Verifying Deployment"
                       sudo docker ps
                       
                       echo "Deployment Successfull"
